[package]
name = "main"
version = "0.1.0"
authors = ["Alan Boglioli <alan.boglioli@gmail.com>"]
edition = "2018"

[[bin]]
name = "omics"
path = "main.rs"

[build-dependencies]
common = { path = "../common" }
identity = { path = "../identity" }
publishing = { path = "../publishing" }


[dependencies]
common = { path = "../common" }
contract = { path = "../contract" }
identity = { path = "../identity" }
publishing = { path = "../publishing" }
subscription = { path = "../subscription" }

serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
