CREATE TABLE IF NOT EXISTS events (
  id UUID PRIMARY KEY,

  topic VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL,

  payload JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,

  permissions JSONB,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,

  provider VARCHAR(16) NOT NULL,
  username VARCHAR(64) UNIQUE NOT NULL,
  email VARCHAR(64) UNIQUE NOT NULL,
  password VARCHAR(128),

  name VARCHAR(64),
  lastname VARCHAR(64),
  birthdate TIMESTAMP WITH TIME ZONE,
  gender VARCHAR(16),
  biography TEXT,
  profile_image VARCHAR(1024),

  role_id VARCHAR(255) REFERENCES roles(id) ON DELETE CASCADE,

  validation_code VARCHAR(255),

  followers INTEGER DEFAULT 0,
  subscribed BOOLEAN DEFAULT FALSE,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS categories (
  id VARCHAR(255) PRIMARY KEY,

  name VARCHAR(255) NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);


CREATE TABLE IF NOT EXISTS collections (
  id UUID PRIMARY KEY,

  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  name VARCHAR(255) NOT NULL,
  synopsis TEXT NOT NULL,
  category_id VARCHAR(255) NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  tags JSONB NOT NULL,
  cover VARCHAR(1024) NOT NULL,

  items JSONB NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS publications (
  id UUID PRIMARY KEY,

  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  name VARCHAR(255) NOT NULL,
  synopsis TEXT NOT NULL,
  category_id VARCHAR(255) NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  tags JSONB NOT NULL,
  cover VARCHAR(1024) NOT NULL,

  contract BOOLEAN DEFAULT FALSE,

  statistics JSONB NOT NULL,
  pages JSONB NOT NULL,

  status_history JSONB NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS publication_status (
  id VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS views (
  id SERIAL PRIMARY KEY,

  reader_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  publication_id UUID NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
  datetime TIMESTAMP WITH TIME ZONE NOT NULL,

  is_unique BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS readings (
  id SERIAL PRIMARY KEY,

  reader_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  publication_id UUID NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
  datetime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
  id SERIAL PRIMARY KEY,

  reader_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  publication_id UUID NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
  datetime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,

  reader_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  publication_id UUID NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
  datetime TIMESTAMP WITH TIME ZONE NOT NULL,

  stars SMALLINT DEFAULT 0,
  comment TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS publication_favorites (
  id SERIAL PRIMARY KEY,

  reader_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  publication_id UUID NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
  datetime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS collection_favorites (
  id SERIAL PRIMARY KEY,

  reader_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  collection_id UUID NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
  datetime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS follows (
  id SERIAL PRIMARY KEY,

  reader_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  datetime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY,

  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code VARCHAR(255) NOT NULL,
  body JSONB NOT NULL,
  read BOOLEAN DEFAULT FALSE,

  datetime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS plans (
  id VARCHAR(255) PRIMARY KEY,

  price DOUBLE PRECISION DEFAULT 0.0,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id UUID PRIMARY KEY,

  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan JSONB NOT NULL,
  payments JSONB NOT NULL,

  status_history JSONB NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS contracts (
  id UUID PRIMARY KEY,

  publication_id UUID NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
  summaries JSONB NOT NULL,
  payments JSONB NOT NULL,

  status_history JSONB NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE,
  deleted_at TIMESTAMP WITH TIME ZONE
);
