clean-db:
	npm run clean-db

populate:
	npm run populate

migrate:
	npm run migrate

api-populate:
	npm run api-populate

old-populate:
	npm run populate

test:
	npm test

update-samples:
	npm run update-samples
