name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo fmt -- --check
    - name: Warnings
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --verbose
